services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: "Asia/Tokyo"
        CLAUDE_CODE_VERSION: "latest"
        GIT_DELTA_VERSION: "0.18.2"
        ZSH_IN_DOCKER_VERSION: "1.2.0"

    volumes:
      - ../..:/workspaces:cached

    # Environment variables for Claude Code
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLAUDE_CONFIG_DIR=/home/vscode/.claude
      - TZ=Asia/Tokyo

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Network capabilities for Claude Code firewall functionality (optional)
    # Uncomment if firewall functionality is needed
    # cap_add:
    #   - NET_ADMIN
    #   - NET_RAW

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    volumes:
      - mssql-data:/var/opt/mssql

    # Add "forwardPorts": ["db:1433"] to **devcontainer.json** to forward MSSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mssql-data:
